# Generated by Django 6.0.1 on 2026-02-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='cost_price',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='pricing',
            name='case_selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
