# Generated by Django 6.0.1 on 2026-02-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_cost_price_pricing_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='case_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='case_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
