# Generated by Django 6.0.1 on 2026-02-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_pricing_case_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
