# Generated by Django 6.0.1 on 2026-02-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_pricing_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
