# Generated by Django 6.0.1 on 2026-05-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_inventorybatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='is_expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
