# Generated by Django 6.0.1 on 2026-04-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='method',
            field=models.CharField(default='cash', max_length=20),
        ),
    ]
