# Generated by Django 6.0.1 on 2026-04-04 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_barcode_alter_product_name'),
        ('sales_monitor', '0002_sale_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='itemTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product'),
            preserve_default=False,
        ),
    ]
